lang: en-UK
url: https://phpwebdevelope.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: 
email: your-email@domain.com
description: ""


# Team names, titles and social links
people:
- name: M. M. 
  pic: 1
  position: Creative Director
  social:
    - title: twitter
      url: https://www.twitter.com/
    - title: facebook
      url:  https://www.facebook.com/
    - title: instagram
      url: https://www.instagram.com/

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: facebook
    url: https://www.facebook.com/
  - title: instagram
    url: https://www.instagram.com/
  - title: google plus 
    url: http://plus.google.com/

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 
  - line:  

# Build settings
markdown: kramdown
permalink: pretty
